// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_M.Students;

#nullable disable

namespace WebAPI_M.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20240223113450_seedPersonModel")]
    partial class seedPersonModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_M.Models.PersonModel", b =>
                {
                    b.Property<int>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personId"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("personName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personId");

                    b.ToTable("PersonModels");

                    b.HasData(
                        new
                        {
                            personId = 1,
                            CreatedTime = new DateTime(2024, 2, 23, 17, 4, 50, 431, DateTimeKind.Local).AddTicks(2042),
                            age = 21,
                            personName = "Praveen"
                        },
                        new
                        {
                            personId = 2,
                            CreatedTime = new DateTime(2024, 2, 23, 17, 4, 50, 431, DateTimeKind.Local).AddTicks(2055),
                            age = 23,
                            personName = "Sandy"
                        },
                        new
                        {
                            personId = 3,
                            CreatedTime = new DateTime(2024, 2, 23, 17, 4, 50, 431, DateTimeKind.Local).AddTicks(2057),
                            age = 22,
                            personName = "Vikram"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
